[versions]
navigationFragment = "2.8.3"
preference = "1.2.1"
activity = "1.9.3"
constraintlayout = "2.2.0"

material = "1.12.0"

dexkit = "2.0.2"
xposed = "82"

appcompatVersion = "1.6.1"
rikkaXMaterial = "2.7.2"
rikkaXPreference = "2.0.0"

agp = "8.7.2"
appcompat = "1.7.0"

[libraries]
preference = { module = "androidx.preference:preference", version.ref = "preference" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigationFragment" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }

dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
libxposed= { group = "de.robv.android.xposed", name = "api", version.ref = "xposed" }

rikkax-appcompat = { module = "dev.rikka.rikkax.appcompat:appcompat", version.ref = "appcompatVersion" }
rikkax-material = { module = "dev.rikka.rikkax.material:material", version.ref = "rikkaXMaterial" }
rikkax-material-preference = { module = "dev.rikka.rikkax.material:material-preference", version.ref = "rikkaXPreference" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

